name: Build
on: { push: { branches: '*' } }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with: { node-version: '20.x' }
    - name: Setup Maintainer Tools
      uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
    - name: Install dependencies
      run: |
        npm install
        python -m pip install -U "jupyterlab>=4.0.0,<5"
    - name: Build the extension
      run: |
        set -eux
        python -m pip install .[test]
        jupyter labextension list
        jupyter labextension list 2>&1 | grep -ie "jupyterlab_toscmode.*OK"
        python -m jupyterlab.browser_check
    - name: Package the extension
      run: |
        set -eux
        pip install build
        python -m build
        pip uninstall -y "jupyterlab_toscmode" jupyterlab
